### ISSUE TITLE
Relay not readable

### ISSUE THREAD

**Issue by hundehausen** [pluja/nerostr#5]
Hey @pluja,

I'm not sure if this is an issue or if I am misunderstanding something.

Please compare 

My relay
https://nostr.watch/relay/nostr.portemonero.com
and your relay
https://nostr.watch/relay/xmr.usenostr.org

Your relay is readable, mine is not. Why is that? Is my reverse proxy configured wrong?

```
nostr.portemonero.com {
	@websockets {
		header Connection *Upgrade*
		header Upgrade websocket
	}

	encode zstd gzip

	reverse_proxy @websockets localhost:7777
	reverse_proxy localhost:8089

	header {
		Access-Control-Allow-Origin *
	}

	handle_path /.well-known* {
		root * /home/hundehausen/well-known
		file_server

		header {
			Access-Control-Allow-Origin *
		}
	}

	handle_path /.public* {
		root * /home/hundehausen/public
		file_server

		header {
			Access-Control-Allow-Origin *
		}
	}
}

``` 

Why could the site not parse NIP-11 information document about our relays?
Does strfry not support NIP-11?

**Comment by pluja** [comment]
Can you try with the latest release? seems like there was a problem (check #6) with the port changes we made (i forgot to release a new version). if that was the problem, I'll close this issue, otherwise I'll check this out further

**Comment by hundehausen** [comment]
Hey @pluja,

I checked everything, my configuration was already correct and since I run watchtower the containers are always running on the latest image.

I figured it out, I think. My Caddyfile was wrong.
When I removed

`encode zstd gzip`

it started working again. Seems nostr or nostr clients don't like compressed traffic.

Thank you for your help! I love nerostr!
