### ISSUE TITLE
Nginx reverse proxy

### ISSUE THREAD

**Issue by alaakaazaam** [pluja/nerostr#6]
Hi pluja,
i’m giving all my time to this docker-compose file and i can say that it starts to finally work : i can access the pay-wall
and add public keys via API (curl cmdline)

Only issue is with nginx reverse-proxy, see : 
nginx doesn’t allow duplicate entrypoint ( here the slash ‘/’)
so i declared 8089 port in yml file and left 7777 port for strfry service

```
server {
    location / {
        proxy_pass http://localhost:8089;
    }

    location /strfry-nerostr-relay {
       proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass http://localhost:7777;
    }
}
```

I tried multiples configurations but all of them hit a wall when clicking ‘Pay-to-relay’ button :
```
{"error":"Post \"http://monero-wallet-rpc:28081/json_rpc\": dial tcp 192.168.0.2:28081: connect: connection refused"}
```

I event tried to replace 'monero-wallet-rpc' with my own monero-node-url [ localhost :) ] but without success

Shouldn’t the vhost file contain those sort of lines, where app2 would be declared in docker-compose.yml ?
```
server {
    listen 80;
    server_name xmr.usenostr.org;

    location / {
        proxy_pass http://nerostr:8089;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /app2/ {
        proxy_pass http://strfry-nerostr-relay:7777;
    }
}
```

Cheers, wish you the best

**Comment by freQniK** [comment]
I am having the same issues with a similar set up

```json
{"error":"Post \"http://monero-wallet-rpc:28081/json_rpc\": dial tcp 172.28.0.3:28081: connect: connection refused"}
```

I tried adding NAT routing rules in the DOCKER chain because `172.28.0.3` didn't exist in there, to no avail however. 

Looking to set this up please advise.

**Comment by freQniK** [comment]
@alaakaazaam I figured this out, change the `--rpc-bind-port` option in the `docker-compose.yml` to be `28081`

```
"--rpc-bind-port",
      "28081",
```

**Comment by pluja** [comment]
Hi, sorry for this, you are right, I have released a new version that should solve this and it won't be necessary to set it to `28081`, so you can leave `18083` which is the default
